#!/usr/bin/env bash

set -xe

DATA_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/line-lancer"
BIN_PATH="$HOME/.local/bin/line-lancer"
DESKTOP_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/applications/line-lancer.desktop"

mkdir -p "$DATA_PATH"

cp -ru assets/* "$DATA_PATH"
cp -u line-lancer "$BIN_PATH"
cp -u line-lancer.desktop "$DESKTOP_PATH"
