#!/usr/bin/env bash

set -xe

if [ -z "$XDG_DATA_HOME" ]; then
    DATA_PATH="$XDG_DATA_HOME/line-lancer"
else
    DATA_PATH="$HOME/.local/share/line-lancer"
fi

BIN_PATH="$HOME/.local/bin/line-lancer"
DESKTOP_PATH="$HOME/.local/share/applications/line-lancer.desktop"

mkdir -p "$DATA_PATH"

cp -ru assets "$DATA_PATH"
cp -u line-lancer "$BIN_PATH"
cp -u line-lancer.desktop "$DESKTOP_PATH"
