#!/usr/bin/env bash

set -xe

DATA_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/line-lancer"
BIN_PATH="$HOME/.local/bin/line-lancer"
DESKTOP_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/applications/line-lancer.desktop"

[ -d "$DATA_PATH" ] && rm -rf "$DATA_PATH"
[ -e "$BIN_PATH" ] && rm "$BIN_PATH"
[ -e "$DESKTOP_PATH" ] && rm "$DESKTOP_PATH"
