#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define FPS 60

#define UNIT_SIZE 6.0f
#define UNIT_SPEED 20.0f

#define BUILDING_SPAWN_INTERVAL 5
#define BUILDING_RESOURCE_INTERVAL 10

#define LAYER_MAP -0.3f
#define LAYER_PATH -0.2f
#define LAYER_BUILDING -0.1f
#define MAP_BEVEL 5

#define RENDER_DEBUG_BRIDGE
#define RENDER_PATHS

#endif // CONSTANTS_H_
